### PR TITLE
Add KE100 Support

### PR DESCRIPTION
**Pull request by delatt**
Adding KE100 TRV Support

### CODE REVIEW

**Comment by delatt** [comment]
@petretiandrea Let me know if there's anything that needs to change :)

**Review by petretiandrea — APPROVED** [review]
Looks great, thanks for your support

**Comment by petretiandrea** [comment]
> @petretiandrea Let me know if there's anything that needs to change :) 

Could you format using black?

**Comment by delatt** [comment]
All done, thanks!

**Comment by jhaboba** [comment]
Thanks for this, it is very useful. I was wondering if you have any insight on how the ke100 controls de valve based on the temperature it reads. I'm aiming to control the boiler from a combined reading of all valves, but I don't want to turn it on while they are all shut.
Thanks!

**Comment by jhaboba** [comment]
> > Thanks for this, it is very useful. I was wondering if you have any insight on how the ke100 controls de valve based on the temperature it reads. I'm aiming to control the boiler from a combined reading of all valves, but I don't want to turn it on while they are all shut. Thanks!
> 
> I honestly have no idea how the valves are controlled based off the temperature but you should be able to tell if a valve is on or off once [petretiandrea/home-assistant-tapo-p100#611](https://github.com/petretiandrea/home-assistant-tapo-p100/pull/611) is merged.

Thanks, that should be even better. Thanks for your work

**Pull request merged**
